# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5e9a07e79fc6b2eacc6d8abd3964849f73277dc44744e77b18f7352778aae75c19fc1988dd4f15a111f208d9927028b86f29d6db55d36807d26366f7044779f

test:
  secret_key_base: ac0a5ea4096ffbc2aefebc753fa4cd37c1f83a01a8e3b5fbe53f0a95692f4df8e3c3284b0a31fc104d4db550b83303550aaa41aad8fc103e7203955a0bbba301

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
